apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../kustomizeconfig

resources:
  - build.yaml

configMapGenerator:
  - name: kaniko-docker-config
    files:
      - config.json
