spring:
  application:
    name: Java DemoApp
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    settings:
      template_exception_handler: rethrow

server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: true
      directory: "/dev"
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:
      pattern: "%t %m %s %U %Dms %Bb"
  error:
    whitelabel:
      enabled: false
  #forward-headers-strategy: framework
  # Without this set the AAD login redirect URL becomes http rather than https
  forward-headers-strategy: native
  use-forward-headers: true

azure:
  activedirectory:
    authorization-clients:
      arm:
        on-demand: true
        scopes: https://management.core.windows.net/user_impersonation
      graph:
        on-demand: true
        scopes:
          - https://graph.microsoft.com/User.Read
    user-group:
      allowed-groups: Users
