image:
  pullPolicy: Always

service:
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: 
    enabled: true
    secretName: kube-benco-io-cert

# Java is SOOOOOO DAMN SLOW to start up
livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 90
  periodSeconds: 30

resources:
  limits:
    cpu: 2000m