image:
  pullPolicy: Always

service:
  targetPort: 8080

secretEnv:
  spring_security_oauth2_client_registration_azure_clientsecret:
    secretName: java-demoapp
    secretKey: aadAppSecret

env: 
  spring_security_oauth2_client_registration_azure_clientid: 0dd79c04-cf6f-48fd-9e49-8ba23f7e7d54
  azure_activedirectory_tenantid: 72f988bf-86f1-41af-91ab-2d7cd011db47

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls: 
    enabled: true
    secretName: kube-benco-io-cert

# Java is SOOOOOO DAMN SLOW to start up
livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 90
  periodSeconds: 30

resources:
  limits:
    cpu: 2000m