image:
  repository: ghcr.io/benc-uk/java-demoapp
  pullPolicy: Always

service:
  targetPort: 8080

secretEnv:
  azure_activedirectory_clientsecret:
    secretName: java-demoapp
    secretKey: aadAppSecret

env:
  azure_activedirectory_clientid: cfc68d9c-bc27-4a18-88c0-63b4438d4f37
  azure_activedirectory_tenantid: 29397eda-722a-44c7-b69c-38e4da1d4f76

ingress:
  enabled: true
  host: java-demoapp.kube.benco.io
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true
    secretName: kube-benco-io-cert

# Java is SOOOOOO DAMN SLOW to start up
livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 90
  periodSeconds: 30

resources:
  limits:
    cpu: 2000m
